server:
  type: simple
  connector:
      type: http
      port: 8010
  applicationContextPath: /order-service
  adminContextPath: /admin
  #disable the registration of default Jersey ExceptionMappers
  registerDefaultExceptionMappers: false

rabbitMq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  exchangeName: "nagp"
  topicNames:
      - "inventory-available-event"
  messageSubscriptions:
      inventory-available-event:
          - msg.event.inventory.available
          - msg.event.inventory.unavailable